[env]
TERM = 'xterm-256color'

[general]
import = [
    "~/.config/alacritty/themes/gruvbox-dark.toml"
]

[window]
opacity = 0.8

# Fonts
[font.normal]
family = 'JetBrains Mono Nerd Font'
style = 'Medium'

[font.italic]
family = 'JetBrains Mono Nerd Font'
style = 'MediumItalic'

[font.bold]
family = 'JetBrains Mono Nerd Font'
style = 'Bold'

# Default colors
# [colors.primary]
# background = '#1e1c31'
# foreground = '#cbe1e7'
# 
# [colors.cursor]
# text = '#ff271d'
# cursor = '#fbfcfc'
# 
# # Normal colors
# [colors.normal]
# black   = '#141228'
# red     = '#ff5458'
# green   = '#62d196'
# yellow  = '#ffb378'
# blue    = '#65b2ff'
# magenta = '#906cff'
# cyan    = '#63f2f1'
# white   = '#a6b3cc'
# 
# # Bright colors
# [colors.bright]
# black   = '#565575'
# red     = '#ff8080'
# green   = '#95ffa4'
# yellow  = '#ffe9aa'
# blue    = '#91ddff'
# magenta = '#c991e1'
# cyan    = '#aaffe4'
# white   = '#cbe3e7'
