[env]
TERM = 'xterm-256color'

[general]
import = [
    "~/.config/alacritty/themes/catppuccin-macchiato.toml"
]

[window]
opacity = 0.8

[window.padding]
x = 5
y = 5

# Fonts
[font.normal]
family = 'JetBrains Mono Nerd Font'
style = 'Medium'

[font.italic]
family = 'JetBrains Mono Nerd Font'
style = 'MediumItalic'

[font.bold]
family = 'JetBrains Mono Nerd Font'
style = 'Bold'
